#!/usr/bin/env python
# encoding: utf-8

from __future__ import print_function

import os
import shlex
import subprocess

"""
Print git branch names
"""

def main():
    HOME=os.getenv('HOME')
    chapel = os.path.abspath(os.path.join(HOME, 'opt', 'dev', 'chapel'))
    chapeldirs = [os.path.join(chapel, d) for d in os.listdir(chapel)]
    chapelrepos = [r for r in chapeldirs if os.path.exists(os.path.join(r, '.git'))]
    for repo in chapelrepos:
        os.chdir(os.path.join(chapel, repo))
        cmd = 'git branch'
        p = subprocess.Popen(shlex.split(cmd), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        p.wait()
        output, err = p.communicate()
        for line in output.split('\n'):
            if '*' in line:
                branch = line.replace('* ', '')
        repository = os.path.split(repo)[-1]
        print('{0:20} : {1}'.format(repository, branch))



if __name__ == '__main__':
    main()

