#!/bin/bash

# Search function for eg

source ~/repos/scripts/lib/bash/colors.sh
source ~/repos/scripts/lib/bash/conditions.sh

Query=$1
Eg="$HOME/repos/eg"

if IsEmptyString $Query; then
    cd $Eg
    ls
    return
fi

# Go to directory in eg named $Query
Dir=`find $Eg -name "$Query"  2> /dev/null`
if ! IsEmptyString $Dir; then
    if IsDirectory $Dir; then
        echo "$Dir is a directory"
        cd $Dir
        ls
        return
    fi
fi

 Open file in eg containing string $Query
Grep=`grep -Hsr $Query $Eg/*`
if ! IsEmpty $Grep; then
    clear
    echo "Lines Found In Files:"
    echo -e "${Purple}---------------------------${NC}"
    echo -e "${Red}`grep -hslr $Query $Eg/* | awk 'BEGIN{FS="/"} {print $(NF)}'`${NC}"
    echo -e "${Purple}---------------------------${NC}"
    echo ""
    echo -e "${Purple}-----------------------------------------------------------------------------------------------------------${NC}"
    grep -hsr --color=auto $Query $Eg/*
    echo -e "${Purple}-----------------------------------------------------------------------------------------------------------${NC}"
    return
fi


