#!/bin/sh

# Clean up all the shit that submitting pbs files creates

# 2.0.e2567015
# 2.0.o2567015

for file in `ls -l | awk '{print $NF}' | egrep '(.*\.[e,o][1-3].*)'`; do
    echo "rm $file"
    rm $file
done

