#!/bin/bash 

# Feed this fun script a PDB ID, and get your PDB file unzipped and ready to go
# All in a blink of the eye!

PDB_ID=$1

wget http://www.rcsb.org/pdb/files/$PDB_ID.pdb.gz &
wait $2
gunzip $PDB_ID.pdb.gz
