#!/usr/bin/env python

from numpy import loadtxt
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

try:
    NOPLOT = False
    from matplotlib import pyplot as plt
except:
    NOPLOT = True



def get_arguments(args=None):
    """
    Get arguments from command line
    :args: Arguments, if predefined
    :returns: Opts, the arguments parsed
    """
    parser = ArgumentParser(prog='plotvfile',
                            usage='%(prog)s Vfile.txt [options] ',
                            description=''' %(prog)s plots Vfile.txt and guesses TS''',
                            formatter_class=ArgumentDefaultsHelpFormatter
                            )
    parser.add_argument('--noplot', default=False, action='store_true', help='Do not plot')

    opts = parser.parse_args(args)

    return opts


def plotvfile(noplot=False):
    """Plot VFile.txt from Q-Chem FSM Output"""
    data = loadtxt('Vfile.txt')
    indices = [x[0] for x in data]
    # relative kcal/mol
    energies = [x[4] for x in data]

    imax = len(energies)-1

    for i in range(len(energies))[::-1]:
        print(i)
        if energies[i] >= energies[imax]:
            imax = i
        else:
            print('TS at point', imax+1)
            print(energies[imax], 'kcal/mol')
            break

    if not noplot:
        plt.scatter(indices, energies)
        plt.show()


if __name__ == "__main__":
    opts = get_arguments()
    if NOPLOT:
        opts.noplot = True
    plotvfile(noplot=opts.noplot)
