#!/bin/bash

# Grep for Q-Chem SCF / CC converged energies
# Eventually implement this into python as qcl e(nergies) ARGS


# True if length of  string is zero

if [ -z $1 ]; then
    target="*.out"
else
    if [ $1 == "-v" ]; then
        target=$2
        if [ -z $2 ]; then
            target="*.out"
        fi
        echo "verbose"
        grep -H "Convergence criterion met" $target
        grep -H "CCSD total energy" $target
        grep -H "MP2         total energy" $target
    elif [ $1 == "-e" ]; then
        target=$2
        if [ -z $2 ]; then
            target="*.out"
        fi
        # New Style (gen_scfman)
        for output in $target; do
            echo "***   Energy Components   ***"
            grep -H "One-Electron    Energy = " $output | tail -1
            grep -H "Total Coulomb   Energy = " $output | tail -1
            grep -H "Total Exchange  Energy = " $output | tail -1
            grep -H "DFT Exchange    Energy = " $output | tail -1
            grep -H "DFT Correlation Energy = " $output | tail -1
            grep -H "Nuclear Attr.   Energy = " $output | tail -1
        done
        # Old Style (scfman)
        #for output in $target; do
        #    echo "***   Energy Components   ***"
        #    grep -H ENuc $output | tail -1
        #    grep -H E1 $output   | tail -1
        #    grep -H EJ $output   | tail -1
        #    grep -H EX $output   | tail -1
        #    grep -H "\*\*\* EC" $target   | tail -1
        #done
    else
        target=$1
    fi
fi

scf=`grep -H "Convergence criterion met" $target | awk '{print $1}' | head -1`
ccsdt=`grep -H " total energy" $target | awk '{print $1}' | head -1`
mp2=`grep -H "MP2         total energy" $target | awk '{print $1}' | head -1`
thankyou=`grep -c "Thank you very much for using Q-Chem.  Have a nice day." $target`

if [ $thankyou -gt 0 ]; then
    echo "Job Completed"
else
    echo "Job Incomplete"
    exit 1
fi

if [ ! -z $scf ]; then
    echo "SCF Energies:"
    grep -H "Convergence criterion met" $target | awk '{print $1, $3}' | tail -1
fi
if [ ! -z $ccsdt ]; then
    echo "CC total energy:"
    grep -H " total energy" $target | awk '{print $1, $6}'
fi
if [ ! -z $mp2 ]; then
    echo "MP2 Energies:"
    grep -H "MP2         total energy" $target | awk '{print $1, $6}'
fi

grep -H "Total job time" $target
grep -H "Optimization Cycle:" $target | tail -1
