#!/bin/bash

# Grep for Q-Chem SCF / CC converged energies
# Eventually implement this into python as qcl e(nergies) ARGS


# True if length of  string is zero
if [ -z $1 ]; then
    echo "SCF Energies:"
    grep "Convergence criterion met" *.out | awk '{print $1, $3}'
    echo "CCSD(T) Energies:"
    grep "CCSD total energy" *.out | awk '{print $1, $6}'
else
    echo "SCF Energies:"
    grep "Convergence criterion met" $1 | awk '{print $1, $3}'
    echo "CCSD(T) Energies:"
    grep "CCSD total energy" $1 | awk '{print $1, $6}'
fi

