#!/bin/bash

# Quick Reference bash script
# Searches $HOME/repos/ref recursively for argument
#   if argument is file, opens file in vim
#   if argument is directory, changes to that directory
#   if argument is a string in file, opens that file 


IsEmpty() {
    if [ -z $1 ]; then
        return 0
    else
        return 1
    fi
}


IsDirectory() {
    if [ -d $1 ]; then
        return 0
    else
        return 1
    fi
}


Query=$1
Ref="$HOME/repos/ref"

# Go to ref
if IsEmpty $Query; then
    cd $Ref
    ls
    return
fi

# Go to directory in ref named $Query
Dir=`find $Ref/$Query -maxdepth 0 2> /dev/null`
if ! IsEmpty $Dir && IsDirectory $Dir; then
    echo "$Dir is a directory"
    cd $Dir
    ls
    return
fi

# Open file in ref named $Query
File=`find $Ref -name "$Query" 2> /dev/null`
if ! IsEmpty $File; then
    vi $File
    return
fi

# Open file in ref containing string $Query
Grep=`grep -Hs $Query $Ref/*`
if ! IsEmpty $Grep; then
    clear
    red='\e[0;31m'
    purple='\e[1;35m'
    NC='\e[0m' # No Color
    echo "Lines Found In Files:"
    echo -e "${purple}---------------------------${NC}"
    echo -e "${red}`grep -hsl $Query $Ref/* | awk 'BEGIN{FS="/"} {print $(NF)}'`${NC}"
    echo -e "${purple}---------------------------${NC}"
    echo ""
    echo -e "${purple}-----------------------------------------------------------------------------------------------------------${NC}"
    grep -hs --color=auto $Query $Ref/*
    echo -e "${purple}-----------------------------------------------------------------------------------------------------------${NC}"
    return
fi



