#!/usr/bin/env python
# encoding: utf-8

from __future__ import print_function
import os


def runall(rundir = os.path.expanduser("~")+'/chemistry/run', compchemsoftware = 'qchem'):
    """
    WORK IN PROGRESS
    Run every job in a given directory
    Options:
    -r --recursively: Search recursively
    -u --unrun-only: Find every un-run job in rundir and run them all
    --compchemsoftware

    Eventually replace qchemall (shitty shell script)
    """

    # Check if data exists and is a directory
    if not os.path.exists(rundir):
        print(rundir, "does not exist")
        exit(1)
    if not os.path.isdir(rundir):
        print(rundir, "is not a directory")
        exit(1)

    # Make a list of all inputs & outputs in rundir, searching recursively
    walk = list(os.walk(rundir))
    for dir in walk:
        for filename in dir[2]:
            # Find inputfiles
            if '.in' in filename:
                # Check if output exists for corresponding inputfile
                outputfilename  = os.path.splitext(filename)[0]+'.out'
                if not outputfilename in dir[2]:
                    inputfile = dir[0] + '/' + filename
                    outputfile = dir[0] + '/' + outputfilename
                    print(compchemsoftware, inputfile, outputfile)



def main(opts=None):
    if opts == None:
        runall()
    else:
        runall(opts.rundir, opts.compchemsoftware)


if __name__ == '__main__':
    exit(main())
