#!/usr/bin/env python
# encoding: utf-8

"""
This script submits Q-Chem jobs to the queue

Authors: Daniel   Lambrecht (original)
         Benjamin  Albrecht (rewritten)
****
If replacing old submit script,
be sure to replace old best_queue as well!
****

New version requires Python 2.7+ (for argparse)

TODO:
    - Improve optimal queue selection
    - Check Limits per queue
    - Read defaults from ~/.submitrc file

"""
# Python3 compatibility
from __future__ import print_function

# Required to check version
import sys

# Standard library imports
try:
    import os, grp, pwd, getpass
    import argparse
    from subprocess import check_output
    import shlex
    from uuid import uuid4
    from imp import load_source
    import best_queue
    import subprocess
except ImportError:
    if sys.version_info < (2,7):
        print("Sorry, submit requires Python 2.7+\n")
        print("If you're on Frank, try:")
        print("module load python/2.7.6-gcc48\n")
        print("or, if you're daring...")
        print("module load python/3.5.0a2")
        sys.exit(1)



def get_arguments(args=None):
    """
    Get arguments from user
    """

    ### Default Settings ###
    # Determine default billing account
    # ... first, determine group(s) that the user belongs to
    # ... then pick the first group as the billing account (most likely the PI's # name)
    user = getpass.getuser()
    groups = [g.gr_name for g in grp.getgrall() if user in g.gr_mem]
    gid = pwd.getpwnam(user).pw_gid
    groups.append(grp.getgrgid(gid).gr_name)
    def_account = groups[0] # default billing account

    # Determine default Q-Chem version
    # We first try $QC environment variable, if that is not defined,
    # we assume we are on Frank and we pick the latest version of the Q-Chem trunk
    def_path = os.environ.get('QC')
    if not def_path:
        qchem_dir = '/home/dlambrecht/software'
        all_subdirs = [qchem_dir + "/" + d for d in os.listdir(qchem_dir) if not os.path.isfile(d) and "qchem" in d and "trunk" in d]
        latest_subdir = max(all_subdirs, key=os.path.getmtime)
        def_path = latest_subdir # default version

    # Argparse parsing
    parser = argparse.ArgumentParser(prog='submit',
                                     usage= "%(prog)s job [options] ",
                                     description = ''' %(prog)s is a script that auto-generates a pbs
                                     file and submits a job, utilizing another script, best_queue, which determines
                                     the best queue to submit for minimizing wait times''',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter
                                    )


    parser.add_argument('job',        type=str, nargs='+', help='Input File')

    parser.add_argument('--program',  type=str,  default='qchem', help='program to run on input file')
    parser.add_argument('--ppn',      type=int,  default=1, help='processors per node')
    parser.add_argument('--nodes',    type=int,  default=1, help='nodes')
    parser.add_argument('--mem',      type=int,  default=-1, help='gb of memory')
    parser.add_argument('--disk',     type=int,  default=-1, help='gb of scratch disk space')
    parser.add_argument('--queue',    type=str,  default='auto', help='queue to submit to, auto for best, aggressive for all')
    parser.add_argument('--walltime', type=str,  default='1:00:00', help='walltime in HH:MM:SS format')
    parser.add_argument('--qos',      type=str,  default='investor', help='priority', choices=['low','investor'])
    parser.add_argument('--account',  type=str,  default=def_account, help='account with Gold on Frank' )
    parser.add_argument('--path',     type=str,  default=def_path, help='path to program')
    parser.add_argument('--save',     action='store_true', help='Save PBS file when True')
    parser.add_argument('--dry',      action='store_true', help='Do not run qsub on PBS file when True')
    parser.add_argument('--investor', type=bool, default=True, help='Add prefix "i" to queue name if you are an investor group')
    parser.add_argument('--email',    type=str,  default='off', help='Email address for job start/finish notifications, set to "off" to turn off')
    parser.add_argument('--jobname',  type=str,  default='off', help='jobname to display in queue')
    parser.add_argument('--qcrc',     action='store_true', help='Use qcrc instead of checking for Q-Chem modules')

    opts = parser.parse_args(args)

    return opts

def choosequeue (opts):
    """
    Automatic selection of submission queue
    """
    if opts.queue == "auto":

        queuetimes = best_queue.main(ppn=opts.ppn, nodes=opts.nodes, mem=opts.mem, disk=opts.disk, walltime=opts.walltime, investor=opts.investor)

        print("Choices of queues:")
        for queuetime in queuetimes:
            print(queuetime[0])

        queue = queuetimes[0][0]
        wait = queuetimes[0][1]

        print("Best submission queue: ", queue)
        print("Estimated wait time: ", wait)

        return queue

def writepbs(opts, jobs):
    """
    Write submission script for batch of jobs
    """

    job_names = [os.path.splitext(job)[0] for job in jobs]
    # Create unique ID for job
    JOB_ID = uuid4().hex # a unique id for the current job
    RUN = "." + job_names[0] + "." + JOB_ID + ".pbs"


    print("run script = ", RUN)

    file = open(RUN, "w")

    file.write("#!/bin/bash\n")
    file.write("\n")

    # Jobname
    if opts.jobname == 'off':
        job_dir = os.path.basename(os.path.dirname(os.path.realpath(job)))
        file.write("#PBS -N " + job_dir + "/" + job_names[0] + "\n")
    else:
        file.write("#PBS -N " + opts.jobname + "\n")

    # Nodes
    file.write("#PBS -l nodes=" + str(opts.nodes) + ":ppn=" + str(opts.ppn) + "\n")

    # Walltime
    file.write("#PBS -l walltime=" + opts.walltime + "\n")

    # Memory
    if opts.mem > 0:
        file.write("#PBS -l mem=" + str(opts.mem) + "gb\n")
        file.write("#PBS -l pmem=" + str(opts.mem) + "gb\n")
    if opts.disk > 0:
        file.write("#PBS -l ddisk=" + str(opts.disk) + "gb\n")

    # Queue
    file.write("#PBS -q " + opts.queue + "\n")

    # Quality of Service
    file.write("#PBS -l qos=" + opts.qos + "\n")

    # Error Logging
    file.write("#PBS -j oe\n")

    # Email Logging
    if not opts.email == "off":
        file.write("#PBS -m abe\n")
        file.write("#PBS -M " + opts.email + "\n")
    file.write("\n")

    # Bash variables
    file.write("NODES=" + str(opts.nodes) + "\n")
    file.write("PPN=" + str(opts.ppn) + "\n")
    file.write("\n")

    # Program
    file.write("# Load Q-Chem Modules\n")
    file.write("module purge\n")
    file.write("module load mpi\n")
    file.write("module load intel/2013.0\n")

    # Modules / qcrc - module manually updated
    # This will load lexigrapically greatest version
    module="qchem/dlambrecht"
    moduleavail = "modulecmd bash avail " + module
    status = check_output(shlex.split(moduleavail), stderr=subprocess.STDOUT)

    if module in status and not opts.qcrc:
        file.write("module load " + module + "\n")
    else:
        qcrc = os.path.join(opts.path, 'qcrc')
        file.write(". " + qcrc+"\n")

    file.write("\n")

    file.write("cd ${PBS_O_WORKDIR}\n")
    for job in jobs:
        file.write("cp ${PBS_O_WORKDIR}/"+job+" ${LOCAL}\n")
    file.write("cd ${LOCAL}\n")
    file.write("\n")

    file.write("run_on_exit() {\n")
    file.write("    set -v\n")
    file.write("    rm $LOCAL/pathtable\n")
    file.write("    cp -v -R $LOCAL/* $PBS_O_WORKDIR\n")
    file.write("}\n")
    file.write("\n")

    file.write("trap run_on_exit EXIT\n")
    file.write("\n")

    file.write('listofjobs="')
    for jobname in job_names:
        file.write(jobname + ' ')
    file.write('"\n')

    parallel_string = ""

    if int(opts.ppn) > 1:
        parallel_string = "-nt ${PPN}"

    save_string = ""
    if opts.save == True:
        save_string = " -save "

    file.write("\n")
    file.write('PROGRAM="`which qchem` ' + parallel_string + save_string + '"\n')
    file.write("\n")

    file.write('i=0\n')
    file.write('for job in $listofjobs; do\n')
    file.write('    let node=($i)*${PPN}+1\n')
    file.write('    host=$(sed -n ${node}p $PBS_NODEFILE)\n')
    file.write('    echo "$job running on $host with ${PPN} cores"\n')
    file.write('    mpirun -np 1 --host $host $PROGRAM $job.qcm $job.out &\n')
    file.write('    let i+=1\n')
    file.write('done\n')

    if opts.save == True:
        file.write("cp -r ${LOCAL}/* ${PBS_O_WORKDIR}/\n")

    file.write("wait\n")
    file.write("rm ${PBS_O_WORKDIR}/" + RUN + "\n")


    file.close()

    return RUN

def submit(RUN):
    """ Wrapper function for qsub / Writes QUID file if aggressively submitting

    :RUN: pbs file to run
    """

    bashCommand = ('qsub '+ RUN)
    status = check_output(shlex.split(bashCommand))

def main():

    # Get arguments using argparse
    opts = get_arguments()

    jobslist = []
    while opts.job:
        jobs = []
        for node in range(opts.nodes):
            jobs.append(opts.job.pop())
            if not opts.job: break
        jobslist.append(jobs)

    for jobs in jobslist:
        print(jobs)
        job_names = [os.path.splitext(job)[0] for job in jobs]
        print("job names = ", job_names)

        if opts.queue == "auto":
            print("auto queue not yet supported for batched jobs")
            sys.exit(1)

        # Write batch script file
        RUN = writepbs(opts, jobs)

        if opts.dry == False:
            submit(RUN)

if __name__ == '__main__':
    main()
